### ISSUE TITLE
Owncloud 7 and 8 shared document editing not working by shared LDAP users

### ISSUE THREAD

**Issue by neazoi** [owncloud/documents#463]
Hello, I have installed Owncloud7 and enabled the LDAP. Users login ok and can share and edit documents at the same time. My data directory is inside the owncloud installation. In the LDAP settings:
User Home Folder Naming Rule is set to uid
Everything works fine with this settings.

However, when I set the User Home Folder Naming Rule to "homeDirectory" (the attribute of my ldap), things are messed up. Let me explain this:
The "homeDirectory" attribute returns the home directory of the LDAP user which is something like /users/m/v/username. If the User Home Folder Naming Rule is set to "homeDirectory", then owncloud creates a folder for each user with the right directory structure, for example /users/m/v/username.
But, when this happens, the documents app is not working correctly. If a user creates a document and shares it with a second user, then the second user cannot edit this document not at the same time, neither when the document owner has closed the file editor.

To test the issue, I have installed ownclowd 8 as well and noticed the same behaviour in owncloud 8.
Also to test the issue, I have made a new clean installation and I have set in the installation wizard, the data directory to be outside the owncloud instance. The same problem happens again.
It seems that is the data directory is outside the owncloud instance, the problem with the documents editing appears.

I am running
mysql Ver 15.1 Distrib 5.5.41-MariaDB, for Linux (x86_64) using readline 5.1
And linux fedora
Linux 3.10.0-123.20.1.el7.x86_64 #1 SMP Thu Jan 29 18:05:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
If you need more info about the issue, please let me know

**Comment by pcletson** [comment]
Hello Neazoi, Karlitschek & RealRancor,
I may be able to add some additional information to this.  I have a new install of OC8.0.2 on Centos6.6 64x with LDAP users and "SetEnvIf Request_URI .*/apps/documents/ajax/.* no-gzip dont-vary" in my .htaccess   I see this same problem as Neazoi.

This is my experience - 
**  For basic OC-Users (ie not LDAP authenticated) Document-App collaboration works perfectly.

** For LDAP users eg LDAP-User1-Group1 - can open or create a new file for editing, make changes and exit with the file saves as normal.
**  LDAP-User1 shares file with User2
**  LDAP-User2 can open the file for editing as usual - provided user1 DOES NOT have the file open at same time.
** User 1 and 2 can open and edit the file as normal provided it does not happen AT SAME TIME
BUT
**  User1 opens file for editing.  Then User2 opens file for editing at same time and the "constant spinner" problem occurs forever.  

##### This happens on simultaneous open:
POST - /apps/documents/ajax/session/joinasuser/xxxx is OK
The browser requests a http-GET with a request token - OC Server replies 404 Error; File not Found
The browser requests twice a http-get with same token - same 404 error
A "will be back later..." message is sent each second = forever

##### Then
On forced exit - User1 can continue to open/edit the file.
User2 can never open the file - the 404 error witht he failed cache token always gets the 404 error.

##### Interesting addition:
If User2 opens the file for editing - THEN User1 opens the file for editing.  It is User1 that will forever have the 404 error.  Even though it is User1 that "owns" the file.

##### Resolution
The only way to resolve the is to delete the file

#######
DATA - This is the inspect data from the HEAD network request that is 404:

Request URL: 	https://storage.au.globalclouds.com/index.php/apps/documents/ajax/genesis/ombasx7luqisxjuudx2ijtm1hi1azx?requesttoken=i1lr0vw0JyDKC3q2a0BtWqY.qTkoAX
Request Method: 	HEAD
Status Code: 	HTTP/1.1 404 Not Found
Request Headers 20:41:25.000
User-Agent:	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0
Referer:	https://storage.au.globalclouds.com/index.php/apps/documents/
Host:	storage.au.globalclouds.com
Connection:	keep-alive
Accept-Language:	en-GB,en;q=0.5
Accept-Encoding:	gzip, deflate
Accept:	text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Sent Cookie
ocw6mf4thzw4:	lgpcise1mqb7emhbeskksorga3
Response Headers Δ78ms
X-XSS-Protection:	1; mode=block
X-Robots-Tag:	none
X-Powered-By:	PHP/5.5.22
X-Frame-Options:	Sameorigin
x-content-type-options:	nosniff
Strict-Transport-Security:	max-age=31536000; includeSubDomains
Server:	Apache/2.2.15
Pragma:	no-cache
Expires:	Thu, 19 Nov 1981 08:52:00 GMT
Date:	Wed, 18 Mar 2015 09:41:25 GMT
Content-Type:	text/html; charset=UTF-8
content-security-policy:	default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *
Connection:	close
Cache-Control:	no-cache, must-revalidate

#######
DATA - This is the inspect data from the two GET network request that is 404:

Request URL: 	https://storage.au.globalclouds.com/index.php/apps/documents/ajax/genesis/ombasx7luqisxjuudx2ijtm1hi1azx?requesttoken=i1lr0vw0JyDKC3q2a0BtWqY.qTkoAX
Request Method: 	GET
Status Code: 	HTTP/1.1 404 Not Found
Request Headers 20:41:25.000
User-Agent:	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0
Referer:	https://storage.au.globalclouds.com/index.php/apps/documents/
Host:	storage.au.globalclouds.com
Connection:	keep-alive
Accept-Language:	en-GB,en;q=0.5
Accept-Encoding:	gzip, deflate
Accept:	text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Sent Cookie
ocw6mf4thzw4:	lgpcise1mqb7emhbeskksorga3
Response Headers Δ93ms
X-XSS-Protection:	1; mode=block
X-Robots-Tag:	none
X-Powered-By:	PHP/5.5.22
X-Frame-Options:	Sameorigin
x-content-type-options:	nosniff
Strict-Transport-Security:	max-age=31536000; includeSubDomains
Server:	Apache/2.2.15
Pragma:	no-cache
Expires:	Thu, 19 Nov 1981 08:52:00 GMT
Date:	Wed, 18 Mar 2015 09:41:26 GMT
Content-Type:	text/html; charset=UTF-8
content-security-policy:	default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *
Content-Length:	0
Connection:	close
Cache-Control:	no-cache, must-revalidate


NOTE - I restrict sharing to group membership.  I have not tested this problem with the sharing-group restriction removed. 

###########################
I hope this information helps move you in a useful direction.  If you feel this issue is unrelated please let me knwo so I may open a new issue.

Thanks

pcletson

**Comment by pcletson** [comment]
This is a screenshot from the inspector:

![oc documents ldap user collaboration error](https://cloud.githubusercontent.com/assets/8174981/6706396/d4c917fc-cda8-11e4-819e-1f2a02dbb8cf.png)

**Comment by nerzhul** [comment]
I have same issue too.
Owncloud 8.0.0-8.0.2
PHP 5.6
Apache 2.2

**Comment by blizzz** [comment]
@VicDeo 

As a LDAP user, I try to open a file I own with documents. This does not work, the spinner does not stop. I see that http://my.server/owncloud/index.php/apps/documents/ajax/genesis/tdt3p4gh97d10ud11ii636nnql5dw4?requesttoken=%20QEwX74AIdh0gYfZ6RC4/vKfB4IrcO always returns 307 redirects until it just stops with the console message »"WARNING: refreshOdf called but ODF was not DONE."« followed by infinite messages of »"will be back later..."«.

![network](https://cloud.githubusercontent.com/assets/2184312/6785028/782713e4-d183-11e4-9a73-64b5e72357bf.png)

Not sure why there is a redirect. Routing issue? … 

I tried to put a simple debug output and die into DocumentController::serve() but this does not seem to be executed, had no effect.

**Comment by VicDeo** [comment]
@blizzz AFAIK status 307 - authorization problem

**Comment by blizzz** [comment]
@VicDeo sorry, typo, 302 redirects, see screenshot.

**Comment by pcletson** [comment]
BUMP
~~ any thoughts from the developer community on this one??

**Comment by VicDeo** [comment]
@blizzz reproduced. Not related to ldap imo.
Partly fixed in master with https://github.com/owncloud/documents/commit/5c4f1a350fc9ed07459a1a32f97dd3700df2c42a
https://github.com/owncloud/documents/pull/483

**Comment by VicDeo** [comment]
Both cherry-picked to stable8  https://github.com/owncloud/documents/pull/485
